# Jekyll configuration
version: v49
author: TGL
author.name: Gatomek
author.email: tomasz.galinski@gmail.com
title: Tytu≈Ç
description: Description
url: gatomek.github.io
markdown: kramdown
theme: minima
#remote_theme: jekyll/minima
rss: false


#plugins:
#  - jekyll-feed

minima:
  skin: classic

header_pages:
  - index.md
  - test.md

